#!/usr/bin/env python3
"""Generate exported target functions for the many-target detach stress test."""

import argparse
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--targets", type=int, required=True)
    args = parser.parse_args()

    if args.targets <= 0:
        parser.error("--targets must be positive")

    lines = [
        "/* Generated by generate_many_targets_stress.py. */",
        "#include <stdint.h>",
        '#include "test_detach_many_targets_stress_generated.h"',
        "",
        "#ifndef PEAK_STRESS_TARGET_COUNT",
        f"#define PEAK_STRESS_TARGET_COUNT {args.targets}",
        "#endif",
        f"#if PEAK_STRESS_TARGET_COUNT != {args.targets}",
        '#error "Generated stress target count does not match compile definition"',
        "#endif",
        "",
        "#define PEAK_STRESS_NOP_SLED \\",
        '    "nop\\n\\t" "nop\\n\\t" "nop\\n\\t" "nop\\n\\t" \\',
        '    "nop\\n\\t" "nop\\n\\t" "nop\\n\\t" "nop\\n\\t" \\',
        '    "nop\\n\\t" "nop\\n\\t" "nop\\n\\t" "nop\\n\\t" \\',
        '    "nop\\n\\t" "nop\\n\\t" "nop\\n\\t" "nop\\n\\t"',
        "",
        "__attribute__((noinline, noclone, used))",
        "static uint64_t peak_detach_stress_leaf(uint64_t value)",
        "{",
        "    uint64_t local = value * UINT64_C(11400714819323198485);",
        '    asm volatile(PEAK_STRESS_NOP_SLED : "+r"(local) : : "memory");',
        "    return local;",
        "}",
        "",
    ]

    for index in range(args.targets):
        variant = index % 5
        lines.append(
            "__attribute__((noinline, noclone, used, externally_visible, visibility(\"default\")))"
        )
        lines.append(f"void peak_detach_stress_target_{index}(uint64_t value)")
        lines.append("{")
        lines.append(f"    uint64_t local = value + UINT64_C({index});")
        if variant == 0:
            lines.append(
                '    asm volatile(PEAK_STRESS_NOP_SLED : "+r"(local) : : "memory");'
            )
        elif variant == 1:
            lines.extend(
                [
                    "    uint64_t scratch[4];",
                    f"    scratch[0] = local ^ UINT64_C({index + 1});",
                    "    scratch[1] = scratch[0] + value;",
                    "    scratch[2] = scratch[1] ^ (local << 3);",
                    "    scratch[3] = scratch[2] + UINT64_C(17);",
                    '    asm volatile("" :: "m"(scratch), "r"(local) : "memory");',
                ]
            )
        elif variant == 2:
            lines.extend(
                [
                    "    if ((value & UINT64_C(1)) == 0) {",
                    "        local ^= local << 7;",
                    "    } else {",
                    "        local += local >> 3;",
                    "    }",
                    '    asm volatile(PEAK_STRESS_NOP_SLED : "+r"(local) : : "memory");',
                ]
            )
        elif variant == 3:
            lines.extend(
                [
                    "    for (uint64_t i = 0; i < UINT64_C(4); i++) {",
                    "        local = (local * UINT64_C(33)) ^ i;",
                    "    }",
                    '    asm volatile("" :: "r"(local) : "memory");',
                ]
            )
        else:
            lines.extend(
                [
                    "    local = peak_detach_stress_leaf(local);",
                    '    asm volatile("" :: "r"(local) : "memory");',
                ]
            )
        lines.append("}")
        lines.append("")

    lines.append("StressTargetFn stress_targets[PEAK_STRESS_TARGET_COUNT] = {")
    for index in range(args.targets):
        lines.append(f"    peak_detach_stress_target_{index},")
    lines.append("};")
    lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
